FROM quay.io/centos-bootc/centos-bootc-cloud:stream9

ADD https://raw.githubusercontent.com/redhat-et/locallm/main/chatbot/quadlet/chatbot.kube.example /etc/containers/systemd/chatbot.kube
ADD https://raw.githubusercontent.com/redhat-et/locallm/main/chatbot/quadlet/chatbot.yaml /etc/containers/systemd/chatbot.yaml
ADD https://raw.githubusercontent.com/redhat-et/locallm/main/chatbot/quadlet/chatbot.image /etc/containers/systemd/chatbot.image

# Change the root password
RUN echo "root:secure" | chpasswd
ADD wheel-passwordless-sudo /etc/sudoers.d/wheel-passwordless-sudo

RUN podman pull --root=/usr/lib/containers/storage quay.io/sallyom/chatbot:inference
RUN dnf install -y vim && dnf clean all
#ADD cuda-rhel9.repo /etc/yum.repos.d/cuda-rhel9.repo

#add nvidia drivers (requires either a released rhel kernel in the base image or dkms) and cuda toolkit
#RUN dnf install -y nvidia-driver nvidia-gds cuda-toolkit && rm /var/log/*.log /var/lib/dnf -rf 
#RUN dnf install -y vim 
