FROM quay.io/centos-bootc/centos-bootc:stream9
RUN dnf update -y && dnf install -y vim-enhanced httpd && dnf clean all

# Substitute YOUR public key below-private key holder for the following public key will have root access
# Alternatively, this section can be removed if configuring users with kickstart or bootc-image-builder
RUN mkdir /usr/etc-system && \
    echo 'AuthorizedKeysFile /usr/etc-system/%u.keys' >> /etc/ssh/sshd_config.d/30-auth-system.conf && \
    echo 'ssh-rsa AAAAB3.....' > /usr/etc-system/root.keys && chmod 0600 /usr/etc-system/root.keys

CMD ["/sbin/init"]

