FROM quay.io/centos-bootc/fedora-bootc:eln
COPY storage.conf /etc/containers/storage.conf
ADD https://raw.githubusercontent.com/sallyom/locallm/add-image-quadlet/chatbot/quadlet/chatbot.kube.example /etc/containers/systemd/chatbot.kube
ADD https://raw.githubusercontent.com/sallyom/locallm/add-image-quadlet/chatbot/quadlet/chatbot.yaml /etc/containers/systemd/chatbot.yaml
ADD https://raw.githubusercontent.com/sallyom/locallm/add-image-quadlet/chatbot/quadlet/chatbot.image /etc/containers/systemd/chatbot.image

# Change the root password
RUN echo "root:secure" | chpasswd
ADD wheel-passwordless-sudo /etc/sudoers.d/wheel-passwordless-sudo

#ADD cuda-rhel9.repo /etc/yum.repos.d/cuda-rhel9.repo

#add nvidia drivers (requires either a released rhel kernel in the base image or dkms) and cuda toolkit
#RUN dnf install -y nvidia-driver nvidia-gds cuda-toolkit && rm /var/log/*.log /var/lib/dnf -rf 
#RUN dnf install -y vim 
