FROM quay.io/centos-bootc/centos-bootc:stream9
COPY wheel-passwordless-sudo /etc/sudoers.d/wheel-passwordless-sudo
RUN dnf update -y && dnf install -y vim httpd && dnf clean all

# The following will set up the root user with ssh access via ssh key-pair. Add your ssh public key in the same way, or,
# uncomment the 2 lines below
#RUN echo "root:secure" | chpasswd
#COPY wheel-passwordless-sudo /etc/sudoers.d/wheel-passwordless-sudo
#
#Substitute YOUR public key for the public keys below-or somalley & dwalsh will have access to your system
RUN mkdir /usr/etc-system && \
    echo 'AuthorizedKeysFile /usr/etc-system/%u.keys' >> /etc/ssh/sshd_config.d/30-auth-system.conf && \
    echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCk9QKBm4nfox+NijF/DYwbS1MB84MD62ucw7aggBjjywTe0TaXogJn95BzT/3bHq8uPBWdx3/YZxXqKjfi/Ac8HG8v31q6DoNJdP6YVy3vx6K3SorhZZJzV2tXTwF3S3AIudTe7NocShoVaFzSIwmzmn7dk5kydcd74Bl4kLZrkUtaMNtRrw6Yadxk1Gktu5NrfHFlKRvtYpK3RVaF+mNyEebp7aXR6i4d1V715AB6jL0GssMgVcIO2xo0zx2H5R25C7JHlxtNPwdap846WfHxNQeH8Up7SM31D/8q+cZ4kjWGFPFti0Ok1vQIMDJbOPnnFvLJp+iTzOBwPSm/cTrp somalley@chandi.usersys.redhat.com' >> /usr/etc-system/root.keys && chmod 0600 /usr/etc-system/root.keys && \
    echo 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA2vfgIjZRMlDQ0ck5ub8S2sfgG1HTML3Y8lsA3yOz/UsVJY/vxnDVrLLZPNk3hLSAVP+W9+j+pF1XsnjQ6aVbrsSxuGkFQvJoZeK3EjZ0A55lqEvJPG9+IUi7rqHBh5yU/ZX9fQ6KkvmB2ECGR1CqOR1uednPJJ/7fHeTElycgOGlYT6hafuo5RV6O3GITA4VAKZdIE+0+N37p0Yej+vIVYG4iRZ7Jgk+ZnZlwyi8IG06CJfuGwpAw76c/rvI6GYYueFwfGjUxo474ReNn53GyBGnM9NtoBdWGFSiPeET7056kfV4TSNDMB24js8lrho3TqE3wl+szkBeKU3oAZ9okQ== dwalsh@localhost.localdomain' >> /usr/etc-system/root.keys && chmod 0600 /usr/etc-system/root.keys

CMD ["/sbin/init"]

